### ISSUE TITLE
[BASICS] To set not used Pins 

### ISSUE THREAD

**Issue by sinapseenergia** [Sinapse-Energia/MIFARE-US#24]
Not used Pins have to be set as reccomended by vendor

http://www.st.com/content/ccc/resource/technical/document/application_note/a2/9c/07/d9/2a/b2/47/dc/CD00004479.pdf/files/CD00004479.pdf/jcr:content/translations/en.CD00004479.pdf

Configuration
An open (floating) pin is a potential hazard to the circuit. 
**I/O pins which are not used in the application should be preferably configured in output low state** 
. This will also minimize the current consumption.A major source of emission in microcontroller 
based applications can be due to high speed digital I/O and communication interfaces such as SPI, I2C clocks, USB or PWM. The Rise/Fall times are critical. Typical designs add RC low pass filters.

**Comment by soporteHW** [comment]
Implemented the following function:

void **_GPIO_default_**(void)

This function defines and sets unused GPIO as shows:
```
GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
GPIO_InitStruct.Pull = GPIO_PULLDOWN;
GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
```
The unused I/O pins are defined in "_**main.h**_" file.
